package com.example.androidproject;

import android.content.ContentValues;
import android.content.Context;
import android.database.Cursor;
import android.database.SQLException;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;

public class DBAdapter {

    //various constants to be used in creating and updating the database
    static final String KEY_ROWID = "_id";          //field autogenerated
    static final String KEY_NAME = "name";          //field
    static final String KEY_PHONE = "phone";
    static final String KEY_EMAIL = "email";        //field
    static final String KEY_ADDRESS = "streetAddress";
    static final String KEY_CITY = "city";
    static final String KEY_PROVINCE= "province";
    static final String KEY_CODE = "postalCode";

    static final String TAG = "DBAdapter";

    static final String DATABASE_NAME = "MyContactsDB";
    static final String DATABASE_TABLE = "mycontacts";
    static final int DATABASE_VERSION = 1;              //if change to 2 recreates db as new version and use 1 to dev

    static final String DATABASE_CREATE =
            "create table mycontacts (_id integer primary key autoincrement, "
                    + "name text not null, phone text not null, email text not null, streetAddress text not null, city text not null, province text not null, postalCode text not null);";

    final Context context;


    private DatabaseHelper dbHelper;
    private SQLiteDatabase db;

    public DBAdapter(Context ctx)   //constructor
    {
        this.context = ctx;
        dbHelper = new DatabaseHelper(context);  //initialize the dbhelper
    }

    private static class DatabaseHelper extends SQLiteOpenHelper    //this starts
    {
        public DatabaseHelper(Context context)
        {
            super(context, DATABASE_NAME, null, DATABASE_VERSION);
            //setting up the object, here it will create db or plug into existing db
        }

        //onCreate implicitly used to create the database table "contacts"
        @Override
        public void onCreate(SQLiteDatabase db)
        {
            try {
                db.execSQL(DATABASE_CREATE);
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }

        //onUpgrade called implicitly when the database "version" has changed, only called on changed versions
        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion)
        {
            Log.w(TAG, "Upgrading database from version " + oldVersion + " to "
                    + newVersion + ", which will destroy all old data");
            db.execSQL("DROP TABLE IF EXISTS mycontacts");
            onCreate(db);
        }
    }

    //---opens the database---
    //calls SQLiteOpenHelper.getWritableDatabase() when opening the DB.
    //If the DB does not yet exist it will be created here.
    public DBAdapter open() throws SQLException
    {
        db = dbHelper.getWritableDatabase();    //just connecting to the db
        return this;
    }

    //---closes the database---
    public void close()
    {
        dbHelper.close();
    }

    //---insert a contact into the database---
    //uses ContentValues class to store key/value pairs for field names and data
    //just changing the variables
    //to be inserted into the DB table by SQLiteDatabase.insert()
    public long insertContact(String name, String phone, String email, String streetAddress, String city, String province, String postalCode)
    {
        ContentValues initialValues = new ContentValues();
        initialValues.put(KEY_NAME, name);
        initialValues.put(KEY_PHONE, phone);
        initialValues.put(KEY_EMAIL, email);
        initialValues.put(KEY_ADDRESS, streetAddress);
        initialValues.put(KEY_CITY, city);
        initialValues.put(KEY_PROVINCE, province);
        initialValues.put(KEY_CODE, postalCode);

      return db.insert(DATABASE_TABLE, null, initialValues);
    }

    //---deletes a particular contact---
    //removes from the DB the record specified using SQLiteDatabase.delete()
    public boolean deleteContact(long rowId)
    {
        return db.delete(DATABASE_TABLE, KEY_ROWID + "=" + rowId, null) > 0;
    }

    //---retrieves all the contacts---
    //SQLiteDatabase.query builds a SELECT query and returns a "Cursor" over the result set
    public Cursor getAllContacts()
    {
        return db.query(DATABASE_TABLE, new String[] {KEY_ROWID, KEY_NAME, KEY_PHONE, KEY_EMAIL, KEY_ADDRESS, KEY_CITY, KEY_PROVINCE, KEY_CODE}, null, null, null, null, null);
        //.query method selects all, these nulls are the search criteria
    }

    //---retrieves a particular contact---
    public Cursor getContact(long rowId) throws SQLException
    {
        Cursor mCursor =
                db.query(true, DATABASE_TABLE, new String[] {KEY_ROWID, KEY_NAME, KEY_PHONE, KEY_EMAIL, KEY_ADDRESS, KEY_CITY, KEY_PROVINCE, KEY_CODE}, KEY_ROWID + "=" + rowId, null,
                        null, null, null, null);
        if (mCursor != null) {
            mCursor.moveToFirst();
        }
        return mCursor; //return cursor to activity to read
    }

    //---updates a contact---
    //Uses SQLiteDatabase.update() to change existing data by key/value pairs
    public boolean updateContact(long rowId, String name, String phone, String email, String streetAddress, String city, String province, String postalCode)
    {
        ContentValues args = new ContentValues();
        args.put(KEY_NAME, name);
        args.put(KEY_PHONE, phone);
        args.put(KEY_EMAIL, email);
        args.put(KEY_ADDRESS, streetAddress);
        args.put(KEY_CITY, city);
        args.put(KEY_PROVINCE, province);
        args.put(KEY_CODE, postalCode);
        return db.update(DATABASE_TABLE, args, KEY_ROWID + "=" + rowId, null) > 0;
        //java normally returns an int not bool

    }

}
